= Asciidoctor Stylesheet Factory
Dan Allen
:toc: preamble
:source: https://github.com/asciidoctor/asciidoctor-stylesheet-factory

This project is a factory for stylesheets that can be used to style the HTML generated by an AsciiDoc processor (specifically the html5 backend).
In addition to being a general purpose AsciiDoc stylesheet generator, it is used to generate the default stylesheet that is bundled with Asciidoctor.

== Foundation

The stylesheets in this project are built using http://compass-style.org[Compass], a CSS authoring framework that uses http://sass-lang.com[Sass] to generate CSS files.
The styles and components are generated by http://foundation.zurb.com[Foundation 5], an awesome and flexible CSS component framework that ensures your stylesheet is cross-browser friendly and mobile friendly.

== Setup and compilation

To setup the project, make sure you have Ruby, RubyGems, Bundler and http://bower.io[Bower].
First, run Bower to install the required web components:

 $ bower install

Then, run Bundler to install the required gems:

 $ bundle

NOTE: The `bundle` command installs all the gems listed in Gemfile.

Once you have the gems installed, you can build the stylesheets.

== Build the stylesheets

To build the stylesheets, simply run:

 $ compass compile

The stylesheets are compiled from the Sass source files in the +sass/+ folder and written to the +stylesheets/+ folder.
You can then reference the stylesheets in +stylesheets/+ from your HTML file.

== Create sample documents

First, create a sample AsciiDoc file, such as:

----
= Introduction to AsciiDoc
Doc Writer <doc@example.com>

A preface about http://asciidoc.org[AsciiDoc].

== First Section

* item 1
* item 2

[source,ruby]
puts "Hello, World!"
----

TIP: Alternatively, you can use this README as an example.

Then, use AsciiDoc or Asciidoctor to generate HTML that uses one of the stylesheets from the +stylesheets/+ directory:

 $ asciidoctor -a stylesheet=./stylesheets/readthedocs.css sample.adoc

If you want to activate syntax highlighting in the code, add this argument:

 -a source-highlighter=highlightjs 

Now just browse to +sample.html+ in your browser and checkout the result!

== External preview

You may want to preview sample HTML files on another computer or device.
To do that, you need to serve them through a web server.
You can quickly serve HTML files in the root directory of the project using the following command:

 python -m SimpleHTTPServer 4242

== Create a new theme

Themes go in the +sass/+ folder.
To create a new theme (e.g., +hipster+), start by creating two new files:

+sass/hipster.scss+::
  * Imports the theme settings, which includes default variables and resets
  * Imports the AsciiDoc components
  * Defines any explicit customizations
+sass/settings/_hipster.scss+::
  * Sets variables that customize Foundation 5 and the AsciiDoc CSS components

Here's a minimal version of +sass/hipster.scss+:

[source,scss]
----
@import "settings/hipster";
@import "components/asciidoc";
@import "components/awesome-icons";
----

NOTE: You don't have to include the underscore prefix when importing files.

NOTE: The +awesome-icons+ component is only applicable to HTML generated by Asciidoctor >= 0.1.2 with the +icons+ attribute set to +font+.

You can add any explicit customizations below the import lines.

The variables you can set in +sass/settings/_hipster.scss+ are a combination of the https://github.com/zurb/foundation/blob/v5.5.0/scss/foundation/_settings.scss[Foundation 5 global settings] and {source}/blob/master/sass/settings/_defaults.scss[default settings and imports for the AsciiDoc components].

Happy theming!
